package fr.miage.syp.publication.data.exception


class ChallengeAlreadyCompletedException : Exception("This challenge is already completed by this user")